In [2]:
import datetime
import logging
import time

import joblib
import pandas as pd
from evidently import ColumnMapping
from evidently.metrics import (
    ColumnDriftMetric,
    DatasetDriftMetric,
    DatasetMissingValuesMetric,
    RegressionQualityMetric
)
from evidently.report import Report

In [3]:
reference_data = pd.read_csv("./data/reference_data.csv")
data = ["./data/result_1.csv","./data/result_2.csv","./data/result_3.csv"]

In [27]:
column_mapping = ColumnMapping(target="actual_duration", prediction="prediction")

report = Report(
    metrics=[
        ColumnDriftMetric(column_name="prediction"),
        DatasetDriftMetric(),
        DatasetMissingValuesMetric(),
        RegressionQualityMetric()
    ]
)

In [28]:
current_data = pd.read_csv("./data/result_1.csv")

In [29]:
report.run(
        reference_data=reference_data, current_data=current_data, column_mapping=column_mapping
    )
results = report.as_dict()

/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:16: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "ref"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "curr"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:16: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "ref"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "curr"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:16: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "ref"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "curr"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:16: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "ref"].groupby("target_binned", observed=False).apply(_apply)
/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/evidently/metrics/regression_performance/utils.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_for_bins[df_for_bins.data == "curr"].groupby("target_binned", observed=False).apply(_apply)

In [14]:
drift_score = results["metrics"][0]["result"]["drift_score"]
num_drifted_columns = results["metrics"][1]["result"]["number_of_drifted_columns"]
share_of_missing_values = results["metrics"][2]["result"]["current"][
        "share_of_missing_values"
    ]

In [34]:
regression_metrics = results["metrics"][3]["result"]

regression_metrics

rmse = regression_metrics["current"]["rmse"]
mae = regression_metrics["current"]["mean_abs_error"]
r2_score = regression_metrics["current"]["r2_score"]

In [40]:
regression_metrics['reference']

{'r2_score': 1.0,
 'rmse': 0.0,
 'mean_error': 0.0,
 'mean_abs_error': 0.0,
 'mean_abs_perc_error': 0.0,
 'abs_error_max': np.float64(0.0),
 'underperformance': {'majority': {'mean_error': nan, 'std_error': nan},
  'underestimation': {'mean_error': 0.0, 'std_error': 0.0},
  'overestimation': {'mean_error': 0.0, 'std_error': 0.0}},
 'error_std': 0.0,
 'abs_error_std': 0.0,
 'abs_perc_error_std': 0.0}

In [35]:
rmse

4.534529914310993

In [36]:
mae

2.8786456638547095

In [15]:
drift_score

np.float64(0.0807295493528422)

In [16]:
num_drifted_columns

1

In [17]:
share_of_missing_values

0.0

In [41]:
reference_data = pd.read_csv("./data/reference_data.csv")

In [42]:
reference_data.head()

,Unnamed: 0.1,Unnamed: 0,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO,prediction,actual_duration
0,0,11202,15,11,1,6,1.0,2.87,74,239,74_239,19.566667,19.566667
1,1,15934,13,15,1,3,1.0,0.96,166,152,166_152,7.866667,7.866667
2,2,26636,10,24,1,5,1.0,1.72,74,75,74_75,9.816667,9.816667
3,3,31073,2,29,1,3,1.0,1.21,129,226,129_226,6.383333,6.383333
4,4,24904,22,22,1,3,1.0,8.17,95,16,95_16,15.933333,15.933333

In [43]:
reference_data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'pickup_hour', 'pickup_day',
       'pickup_month', 'pickup_weekday', 'passenger_count', 'trip_distance',
       'PULocationID', 'DOLocationID', 'PU_DO', 'prediction',
       'actual_duration'],
      dtype='object')

In [47]:
reference_data.drop(columns = ['Unnamed: 0.1', 'Unnamed: 0'],axis=1,inplace=True)

In [48]:
reference_data.to_csv('./data/reference_data.csv',index=False)

In [49]:
reference_data.head()

,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO,prediction,actual_duration
0,15,11,1,6,1.0,2.87,74,239,74_239,19.566667,19.566667
1,13,15,1,3,1.0,0.96,166,152,166_152,7.866667,7.866667
2,10,24,1,5,1.0,1.72,74,75,74_75,9.816667,9.816667
3,2,29,1,3,1.0,1.21,129,226,129_226,6.383333,6.383333
4,22,22,1,3,1.0,8.17,95,16,95_16,15.933333,15.933333

In [24]:
reference_data['actual_duration'] = reference_data['prediction']

In [50]:
reference_data.columns

Index(['pickup_hour', 'pickup_day', 'pickup_month', 'pickup_weekday',
       'passenger_count', 'trip_distance', 'PULocationID', 'DOLocationID',
       'PU_DO', 'prediction', 'actual_duration'],
      dtype='object')

In [51]:
current_data.columns

Index(['pred_id', 'Unnamed: 0', 'pickup_hour', 'pickup_day', 'pickup_month',
       'pickup_weekday', 'passenger_count', 'trip_distance', 'PULocationID',
       'DOLocationID', 'PU_DO', 'prediction', 'prediction_time',
       'actual_duration'],
      dtype='object')

In [25]:
reference_data.head()

,Unnamed: 0,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO,prediction,actual_duration
0,11202,15,11,1,6,1.0,2.87,74,239,74_239,19.566667,19.566667
1,15934,13,15,1,3,1.0,0.96,166,152,166_152,7.866667,7.866667
2,26636,10,24,1,5,1.0,1.72,74,75,74_75,9.816667,9.816667
3,31073,2,29,1,3,1.0,1.21,129,226,129_226,6.383333,6.383333
4,24904,22,22,1,3,1.0,8.17,95,16,95_16,15.933333,15.933333

In [26]:
reference_data.to_csv("./data/reference_data.csv")